name = "Fabulously Optimized"
author = "robotkoer"
version = "14.0.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3976bb9fbc2ab3aaa01d18dfa443aed42c19ceb68185eec32e601a29f700ca87"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
